bug(issue): Support explicit transitions for issues
foxythemes/jira-cli pull request #39
Opened 2019-08-01 18:42 UTC by dancrumb

The CLI was ignoring transition names when it came to
`jira i XXX --transition YYY`. This fixes that.

Fixes #38

2019-11-24 16:01 UTC, miguelmich requested changes

2019-11-24 16:01 UTC, miguelmich commented on src/issues.js
> +    if (transitionName) {
@dancrumb excellent! just one little detail, can you please add an additional check here, the transitionName is returning `true` if there is no parameter, so we need to introduce something like `if (transitionName && transitionName !== true) {` what do you think?

2019-11-24 17:26 UTC, dancrumb commented on src/issues.js
> +    if (transitionName) {
I think this will do it

```suggestion
    if (typeof transitionName === 'string' && transitionName.length > 0) {
```

2019-12-09 00:56 UTC, merged

2022-10-22 16:50 UTC, rdourado commented
Why wasn't this released?

2022-10-22 17:04 UTC, dancrumb commented
Looks like the last release was 6 months prior to this merge :/